apiVersion: v1
kind: Service
metadata:
  name: {{ include "service.name" . }}
spec:
  type: LoadBalancer
  selector:
    {{- include "service.selectorLabels" . | nindent 4 }}
  ports:
  - port: 80
    targetPort: http
    protocol: TCP
    name: http
